---
# tasks file for httpd
- name: install httpd package
  yum:
    name: httpd
    state: latest
- name: start and enable httpd service
  service:
    name: httpd
    enabled: yes
    state: started
...
